[profile.default]
src = "src"
out = "out"
libs = ["lib"]
exclude = ["lib/v4-periphery/lib/permit2/"]
solc_version = "0.8.26"
evm_version = "cancun"
viaIR = true
optimizer = true
optimizer_runs = 3000
[profile.rpc-endpoints]
unichain_sepolia = "https://unichain-sepolia.g.alchemy.com/v2/${UNICHAIN_SEPOLIA_RPC_API_KEY}"


[etherscan]

unichain-sepolia-api = { key = "${UNICHAIN_SEPOLIA_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
