[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
remappings = [
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@solmate/=lib/solmate/src/",
    "@balancer-labs/v3-interfaces/=lib/balancer-v3-monorepo/pkg/interfaces/",
    "forge-std/=lib/forge-std/src"
]

[profile.rpc-endpoints]
unichain_sepolia = "https://unichain-sepolia.g.alchemy.com/v2/${UNICHAIN_SEPOLIA_RPC_API_KEY}"


[etherscan]

unichain-sepolia-api = { key = "${UNICHAIN_SEPOLIA_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
