[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1_000
solc_version = "0.8.26"
evm_version = "cancun"


[profile.ci]

fuzz = { runs = 5000 }
invariant = { runs = 1000 }
[profile.lite]

fuzz = { runs = 50 }
invariant = { runs = 10 }
optimizer = false

[rpc-endpoints]
unichain-sepolia = "${UNICHAIN_SEPOLIA_RPC_URL}"


[etherscan]

unichain-sepolia-api = { key = "${UNICHAIN_SEPOLIA_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
