[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
viaIR = true
optimizer = true
optimizer_runs = 3000
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "bunni-v2/=lib/bunni-v2/",
    "@jit-sample/=lib/jitterbug/",
    "@openzeppelin/uniswap-hooks/=lib/uniswap-hooks/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@euler-swap/=lib/euler-swap/",
    "@openzeppelin-upgradeable/contracts/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "solmate/src/=lib/solmate/src/"
]

[profile.rpc-endpoints]
unichain_sepolia = "https://unichain-sepolia.g.alchemy.com/v2/${UNICHAIN_SEPOLIA_RPC_API_KEY}"


[etherscan]

unichain-sepolia-api = { key = "${UNICHAIN_SEPOLIA_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
